### ISSUE TITLE
Should we use card data object directly in ModelCard.from_template?

### ISSUE THREAD

**Issue by nateraw** [nateraw/modelcards#19]
Right now, the `ModelCard.from_template` function takes in the same args as `CardData`, and then just initializes it. Does it make more sense to initialize CardData separately and pass that to `ModelCard.from_template`? That way the documentation around card data is all in one place.

So instead of

```python
card = ModelCard.from_template(language='en', ...)
```
you would do

```python
card_data = CardData(language='en', ...)
card = ModelCard.from_template(card_data, **template_kwargs)
```

CC @adrinjalali

**Comment by nateraw** [comment]
Also CC @mgerchick if you have any thoughts here

**Comment by adrinjalali** [comment]
Yeah that looks reasonable to me.
