### ISSUE TITLE
Support Evaluation Metrics in Card Data

### ISSUE THREAD

**Issue by nateraw** [nateraw/modelcards#3]
We should be able to add/update model card evaluation metrics in the modelcard metadata (the stuff that is in between the `---`s). These updates/additions to model card evaluation data should be validated to make sure no problems occur when pushing to the hub (RE: #2 ).

**Comment by nrajani** [comment]
We are working on this for Autoeval and currently, we decided to add it to dataset metadata as opposed to the model https://github.com/huggingface/autonlp-backend/issues/414

**Comment by nateraw** [comment]
Very helpful link, thank you @nrajani 😄 

Some tooling work around this exists in `huggingface_hub` as well (which looks like its linked in the issue you just shared above):

Model Index Metadata data validation types: https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/repocard_types.py

Usage to update model index metadata:
https://github.com/huggingface/huggingface_hub/blob/65d3c88a24b648dd65ad76d78f11d76c45a7083c/src/huggingface_hub/repocard.py#L198-L233
