### ISSUE TITLE
Should we update syntax for loading model cards?

### ISSUE THREAD

**Issue by nateraw** [nateraw/modelcards#4]
So right now, I have it so `ModelCard.load` works for both repo IDs and local files.

I'm thinking perhaps we could do:
-  `ModelCard.open(filepath)` to open a local file
-  `ModelCard.load_from_hub(repo_id)` to load a remote Hugging Face model repo model card

WDYT?

**Comment by julien-c** [comment]
`.load()` is fine IMO

**Comment by nateraw** [comment]
Thank you for the feedback!! Its nice to not talk to yourself...
